### ISSUE TITLE
Modification List

### ISSUE THREAD

**Issue by skim0119** [skim0119/PyElastica-to-Rhino#1]
## Todo List

- [x] Render module should have a boolean receiver that tells all the previous operations are finished.
- [x] Bake module should have boolean output that tells all bake is finished.
- [x] Layer Name
- [x] <s>Time dilatation module might be useful, but require interpolation algorithm in .NET</s> (Handled outside of gh)
- [x] Sphere
- [x] <s>Cylinder</s>
- [ ] Multiple camera view (rasterize)
- [ ] More option available for rasterize rendering
- [ ] Activation visualization
- [ ] Strain visualization

---

- [x] Threading
- [x] Finalize the project and build in release mode. (install in noye)
- [ ] Mac installation

---

## Documentation
 - [ ] Tutorial on modules
 - [ ] Example cases
   - [ ] Camera feature
   - [ ] import - load - bake
   - [ ] render
   - [ ] handling multiple data
